version: '3.8'
services:
  # PostgreSQL database for comments
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=portfolio
    ports:
      - "5432:5432"
  
  # Backend service with API endpoints for comments
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=portfolio
      - PGPORT=5432
    depends_on:
      - db
  
  # Frontend service
  frontend:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
