version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/db.sqlite:/app/db.sqlite
    env_file:
      - ./backend/.env
  frontend:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
